checks:
  polaris:
    runAsRootAllowed:
      severity: high
      ci:
        block: false
      admission:
        block: false
    privilegeEscalationAllowed:
      severity: high
      admission:
        block: false
    livenessProbeMissing:
      severity: medium
      ci:
        block: false
      admission:
        block: false
    cpuLimitsMissing:
      ci:
        block: false
    cpuRequestsMissing:
      ci:
        block: false
    memoryLimitsMissing:
      ci:
        block: false
    memoryRequestsMissing:
      ci:
        block: false
  opa:
    label-required:
      ci:
        block: false
    finops-labels:
      ci:
        block: false
      admission:
        block: false  
    default-namespace:
      admission:
        block: true      
     