checks:
  polaris:
    runAsRootAllowed:
      severity: medium
    privilegeEscalationAllowed:
      severity: high
      admission:
        block: true
    livenessProbeMissing:
      severity: high
      ci:
        block: false
      admission:
        block: true
    cpuLimitsMissing:
      ci:
        block: true
    cpuRequestsMissing:
      ci:
        block: true
    memoryLimitsMissing:
      ci:
        block: true
    memoryRequestsMissing:
      ci:
        block: true
  opa:
    label-required:
      ci:
        block: true
    finops-labels:
      ci:
        block: true
    dont-deploy-into-certain-namespaces:
      admission:
        block: true      
     