checks:
  polaris:
    runAsRootAllowed:
      severity: medium
    privilegeEscalationAllowed:
      severity: medium
      admission:
        block: false
    livenessProbeMissing:
      severity: medium
      ci:
        block: true
      admission:
        block: false
    cpuLimitsMissing:
      ci:
        block: true
    cpuRequestsMissing:
      ci:
        block: true
    memoryLimitsMissing:
      ci:
        block: true
    memoryRequestsMissing:
      ci:
        block: true
  opa:
    label-required:
      ci:
        block: true
     